### ISSUE TITLE
Couldn't send twins

### ISSUE THREAD

**Issue by maxtar** [husarlabs/iothub#1]
Hi, I try to send updated twins to server but nothing to do on server side. Next time I receive old twins.
Use the following code:
```go
c, err := iotdevice.NewClient(
		iotdevice.WithTransport(mqtt.New()),
		iotdevice.WithX509FromCert(DeviceID, Hostname, &crt),
	)

if v, err := c.UpdateTwinState(ctx, stateTwin); err != nil {
		log.Fatalf("Error send twins update: %v", err)
	} else {
		log.Printf("New twins settings: %v\n", v)
	}
```
, where `crt` - certificate from pem files.

**Comment by sirKaskadir** [comment]
Hi :) 

Unfortunetaly I don't have good news for you guys.
This is not our library orignally - we didn't want to fork it but it disappeared from github after few days after we've cloned it so we've just created our own repo.

So I'm afraid that we have no knowledge and resources to help you.

Good luck!

**Comment by maxtar** [comment]
@sirKaskadir Wow, it's a pity. That's interesting situation... Thanx for answer.
